// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timberborn.Infrastructure.Data;

#nullable disable

namespace Timberborn.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322151755_AddLeverOnOffUrls")]
    partial class AddLeverOnOffUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Timberborn.Core.Models.ActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AdapterLogId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AutomationRuleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LeverId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CalledAt");

                    b.HasIndex("LeverId");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("Timberborn.Core.Models.Adapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Adapters");
                });

            modelBuilder.Entity("Timberborn.Core.Models.AdapterLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TriggeredAnyRule")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdapterId");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("AdapterLogs");
                });

            modelBuilder.Entity("Timberborn.Core.Models.AutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LeverId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdapterId");

                    b.HasIndex("LeverId");

                    b.ToTable("AutomationRules");
                });

            modelBuilder.Entity("Timberborn.Core.Models.Lever", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyTemplate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlOff")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Levers");
                });

            modelBuilder.Entity("Timberborn.Core.Models.ActionLog", b =>
                {
                    b.HasOne("Timberborn.Core.Models.Lever", "Lever")
                        .WithMany()
                        .HasForeignKey("LeverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lever");
                });

            modelBuilder.Entity("Timberborn.Core.Models.AdapterLog", b =>
                {
                    b.HasOne("Timberborn.Core.Models.Adapter", "Adapter")
                        .WithMany("Logs")
                        .HasForeignKey("AdapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adapter");
                });

            modelBuilder.Entity("Timberborn.Core.Models.AutomationRule", b =>
                {
                    b.HasOne("Timberborn.Core.Models.Adapter", "Adapter")
                        .WithMany("Rules")
                        .HasForeignKey("AdapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timberborn.Core.Models.Lever", "Lever")
                        .WithMany()
                        .HasForeignKey("LeverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adapter");

                    b.Navigation("Lever");
                });

            modelBuilder.Entity("Timberborn.Core.Models.Adapter", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
